//HintName: Grpc.Proxy.Tests.Proto.Test.TestClient.gen.cs
// <auto-generated>
//     Generated by the gRPC Proxy.  DO NOT EDIT!
//     service: a.b.c.d.Test
// </auto-generated>
namespace Grpc.Proxy.Tests.Proto;

public static partial class Test
{
    public partial class TestClient : ITestClient
    {
    }
}